/**
 * Created by Yurek on 2016/12/20.
 */
export const ROUTECHANGE = 'ROUTECHANGE';
export const HISOTRYBACKSTYLE = 'HISOTRYBACKSTYLE';
export const HISOTRYBACK = 'HISOTRYBACK';
export const FETCHMODAL_SHOW   = 'FETCHMODAL_SHOW';
export const FETCHMODAL_HIDDEN = 'FETCHMODAL_HIDDEN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAILURE = 'GETUSER_FAILURE';

export const SAVE_NAV = 'SAVE_NAV'